### ISSUE TITLE
VisualEditor not working

### ISSUE THREAD

**Issue by paulpach** [ubc/mediawiki-docker#19]
Latest release includes wikimedia 1.32

according to this matrix:  https://www.mediawiki.org/wiki/Extension:VisualEditor#Linking_with_Parsoid

there is no tested version of parsoid.   The version you are using comes from mediawiki-node-services which is very old.

I ran this, with only VisualEditor extension and I get this error when trying to save a page:

```
2020-05-19T02:40:12.487054909Z {"name":"mediawiki-node-services","hostname":"d8e814730cff","pid":16,"level":30,"logType":"info","wiki":"localhost","title":"Main_Page","oldId":8,"reqId":"08f81f80-997a-11ea-87c6-e576a1397a8f","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36","msg":"completed wt2html in 8208.955689966679ms","longMsg":"completed wt2html in 8208.955689966679ms","levelPath":"info","time":"2020-05-19T02:40:12.486Z","v":0}
2020-05-19T02:40:12.705994009Z {"name":"restbase","hostname":"d8e814730cff","pid":16,"level":20,"message":"500: internal_error","res":{"status":500,"headers":{"access-control-allow-origin":"*","access-control-allow-methods":"GET,HEAD","access-control-allow-headers":"accept, content-type, content-length, cache-control, accept-language, api-user-agent, if-match, if-modified-since, if-none-match, dnt, accept-encoding","access-control-expose-headers":"etag","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","referrer-policy":"origin-when-cross-origin","x-xss-protection":"1; mode=block","content-security-policy":"default-src 'none'; frame-ancestors 'none'","x-content-security-policy":"default-src 'none'; frame-ancestors 'none'","x-webkit-csp":"default-src 'none'; frame-ancestors 'none'","cache-control":"private, max-age=0, s-maxage=0, must-revalidate","x-request-id":"08f81f80-997a-11ea-87c6-e576a1397a8f","server":"d8e814730cff"}},"stack":"TypeError: siteInfo.baseUri.replace is not a function\n    at mwUtil.getSiteInfo.then (/src/node_modules/restbase/sys/parsoid.js:156:42)\n    at tryCatcher (/src/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/src/node_modules/bluebird/js/release/promise.js:517:31)\n    at Promise._settlePromise (/src/node_modules/bluebird/js/release/promise.js:574:18)\n    at Promise._settlePromise0 (/src/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/src/node_modules/bluebird/js/release/promise.js:699:18)\n    at _drainQueueStep (/src/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/src/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/src/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues (/src/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)","latency":12328,"root_req":{"method":"get","uri":"/localhost/v1/page/html/Main_Page?redirect=false","headers":{"cache-control":"no-cache","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36","api-user-agent":"VisualEditor-MediaWiki/1.32.1","x-client-ip":"24.182.119.248","x-forwarded-for":"24.182.119.248:54682, 172.16.32.1, ::ffff:172.16.32.4","x-request-id":"08f81f80-997a-11ea-87c6-e576a1397a8f","x-request-class":"external"}},"request_id":"08f81f80-997a-11ea-87c6-e576a1397a8f","levelPath":"debug/request/slow","msg":"500: internal_error","time":"2020-05-19T02:40:12.705Z","v":0}
2020-05-19T02:40:12.707032176Z {"name":"restbase","hostname":"d8e814730cff","pid":16,"level":50,"message":"500: internal_error","res":{"name":"HTTPError","message":"500: internal_error","status":500,"body":{"type":"internal_error","description":"TypeError: siteInfo.baseUri.replace is not a function"},"innerError":{"requestName":"get_from_backend"},"headers":{"access-control-allow-origin":"*","access-control-allow-methods":"GET,HEAD","access-control-allow-headers":"accept, content-type, content-length, cache-control, accept-language, api-user-agent, if-match, if-modified-since, if-none-match, dnt, accept-encoding","access-control-expose-headers":"etag","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","referrer-policy":"origin-when-cross-origin","x-xss-protection":"1; mode=block","content-security-policy":"default-src 'none'; frame-ancestors 'none'","x-content-security-policy":"default-src 'none'; frame-ancestors 'none'","x-webkit-csp":"default-src 'none'; frame-ancestors 'none'","cache-control":"private, max-age=0, s-maxage=0, must-revalidate","x-request-id":"08f81f80-997a-11ea-87c6-e576a1397a8f","server":"d8e814730cff"}},"stack":"TypeError: siteInfo.baseUri.replace is not a function\n    at mwUtil.getSiteInfo.then (/src/node_modules/restbase/sys/parsoid.js:156:42)\n    at tryCatcher (/src/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/src/node_modules/bluebird/js/release/promise.js:517:31)\n    at Promise._settlePromise (/src/node_modules/bluebird/js/release/promise.js:574:18)\n    at Promise._settlePromise0 (/src/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/src/node_modules/bluebird/js/release/promise.js:699:18)\n    at _drainQueueStep (/src/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/src/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/src/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues (/src/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)","latency":12328,"root_req":{"method":"get","uri":"/localhost/v1/page/html/Main_Page?redirect=false","headers":{"cache-control":"no-cache","user-agent":"Mozilla/5.0 
```

**Comment by xcompass** [comment]
Hi, we are still on REL1_31. If you use mediawiki 1.31,  you can try ubcctlt/mediawiki-node-services:REL1_31 (https://hub.docker.com/r/ubcctlt/mediawiki-node-services/tags). 

Haven't found a working version of parsoid with REL1_32. And we may skip to 1.35 when it's release.

**Comment by paulpach** [comment]
Thank you,  downgraded to REL1_31 and it seems to be working.
